name: f2f_benchmarks
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - lightning
  - numpy=1.26
  - pip:
    - -r requirements_benchmarks.txt